<?php echo $this->headScript()->appendFile('../lib/centralized.js'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN" "http://www.w3.org/TR/html4/strict.dtd">-->
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>  
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl.('../css/index.css'));?>
        <meta name="google-site-verification" content="LXg0Y_JIG6l-wDWTtIQmmRsnakD-wXRxCrADYcMGhE0" />
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>SISCON - Sistema de Controle Interno</title>
    </head>
    <body>
        <div class="tudo">
            <div class="panel-heading">
                <img  src="../imagens/SISCon-logo.png" id='topo'>
            </div>
            
            <div class="container">
                <?php echo $this->layout()->content ?>
            </div>
                
            <div class="panel-footer">
                <p>Desenvolvido por: ® Douglas Mariz - Todos os direitos reservados. | 2014 |</p>
            </div>
        </div>
    </body>
</html>
